(() => {
'use strict';
const DATA = window.PSW_DATA || {records:[],audit:{}};
const ACADEMIC_GROUPS=['ภาษาไทย','คณิตศาสตร์','วิทยาศาสตร์และเทคโนโลยี','สังคมศึกษา ศาสนาและวัฒนธรรม','สุขศึกษาและพลศึกษา','ศิลปะ','การงานอาชีพ','ภาษาต่างประเทศ'];
const PASS=['4','3.5','3','2.5','2','1.5','1'], NUM=['4','3.5','3','2.5','2','1.5','1','0'], ALL=[...NUM,'ร','มส'], G3=['4','3.5','3'];
const COLORS={old:'#94A3B8',now:'#2563EB',green:'#16A34A',red:'#DC2626',orange:'#F59E0B',purple:'#7C3AED'};
const state={page:'overview',grade:'all',group:'all',subject:'all',scene:0,charts:{}};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=(n,d=2)=>n==null||Number.isNaN(n)?'ไม่มีข้อมูล':Number(n).toLocaleString('th-TH',{minimumFractionDigits:d,maximumFractionDigits:d});
const pct=n=>n==null?'ไม่มีข้อมูล':fmt(n)+'%';
const diffText=n=>n==null?'ไม่สามารถคำนวณได้':`${n>0?'▲ +':n<0?'▼ ':'− '}${fmt(Math.abs(n))} จุดร้อยละ`;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const sum=(arr,fn)=>arr.reduce((a,x)=>a+(fn?fn(x):x),0);
function academic(records){return records.filter(r=>ACADEMIC_GROUPS.includes(r.subjectGroup));}
function filtered(year){return academic(DATA.records).filter(r=>String(r.year)===String(year) && (state.grade==='all'||r.gradeLevel===state.grade) && (state.group==='all'||r.subjectGroup===state.group) && (state.subject==='all'||r.subjectCode===state.subject));}
function metric(records){
  const total=sum(records,r=>sum(ALL,k=>r.grades[k]||0));
  const pass=sum(records,r=>sum(PASS,k=>r.grades[k]||0));
  const fail=sum(records,r=>(r.grades['0']||0)+(r.grades['ร']||0)+(r.grades['มส']||0));
  const g3=sum(records,r=>sum(G3,k=>r.grades[k]||0));
  const numericN=sum(records,r=>sum(NUM,k=>r.grades[k]||0));
  const points=sum(records,r=>sum(NUM,k=>parseFloat(k)*(r.grades[k]||0)));
  return {total,pass,fail,passRate:total?pass/total*100:null,failRate:total?fail/total*100:null,g3Rate:total?g3/total*100:null,gpa:numericN?points/numericN:null,zero:sum(records,r=>r.grades['0']||0),r:sum(records,r=>r.grades['ร']||0),ms:sum(records,r=>r.grades['มส']||0),numericN};
}
function enrollment(records){
  const levels=[...new Set(records.map(r=>r.gradeLevel).filter(Boolean))];
  return Math.round(sum(levels,g=>Math.max(0,...records.filter(r=>r.gradeLevel===g).map(r=>r.studentCount||0))));
}
function groupMetrics(year,key){const rec=filtered(year);const keys=[...new Set(rec.map(r=>r[key]).filter(Boolean))];return keys.map(k=>({key:k,m:metric(rec.filter(r=>r[key]===k))}));}
function compareRows(key){
  const a=groupMetrics('2568',key), b=groupMetrics('2569',key), keys=[...new Set([...a.map(x=>x.key),...b.map(x=>x.key)])];
  return keys.map(k=>{const x=a.find(z=>z.key===k)?.m||metric([]), y=b.find(z=>z.key===k)?.m||metric([]);return {key:k,a:x,b:y,d:(x.passRate!=null&&y.passRate!=null)?y.passRate-x.passRate:null};});
}
function trendClass(v,goodWhenUp=true){if(v==null||Math.abs(v)<.005)return 'neutral';return (goodWhenUp?v>0:v<0)?'good':'bad';}
function kpiCard(label,a,b,{subtitle='',featured=false,reverse=false,kind='pct'}={}){const d=(a!=null&&b!=null)?b-a:null;const val=x=>kind==='count'?fmt(x,0):kind==='gpa'?fmt(x):pct(x);return `<article class="kpi ${featured?'featured':''}"><div class="label">${label}</div>${subtitle?`<div style="font-size:10px;color:#94a3b8;margin-top:3px">${subtitle}</div>`:''}<div class="big">${val(b)}</div><div class="pair"><span>1/2568 <b>${val(a)}</b></span><span>1/2569 <b>${val(b)}</b></span></div><div class="trend ${trendClass(d,!reverse)}">${kind==='pct'?diffText(d):d==null?'ไม่สามารถคำนวณได้':`${d>0?'▲ +':d<0?'▼ ': '− '}${fmt(Math.abs(d),kind==='count'?0:2)}${kind==='count'?' คน':''}`}</div></article>`}
function renderKPIs(){const a=metric(filtered('2568')),b=metric(filtered('2569')),e68=enrollment(filtered('2568')),e69=enrollment(filtered('2569'));const grades=compareRows('gradeLevel').filter(x=>x.d!=null).sort((x,y)=>y.d-x.d);const best=grades[0];$('#kpis').innerHTML=[kpiCard('ผ่านเกณฑ์',a.passRate,b.passRate,{subtitle:'เกรด 1 ขึ้นไป และไม่ติด 0 / ร / มส',featured:true}),kpiCard('0 / ร / มส',a.failRate,b.failRate,{subtitle:'สัดส่วนไม่ผ่านเกณฑ์',reverse:true}),kpiCard('เกรด 3 ขึ้นไป',a.g3Rate,b.g3Rate),kpiCard('GPA เฉลี่ย',a.gpa,b.gpa,{kind:'gpa'}),kpiCard('จำนวนนักเรียน',e68,e69,{kind:'count',subtitle:'ยอดสูงสุดรายชั้น ไม่ใช่ Unique Student จากทะเบียน'}),`<article class="kpi"><div class="label">พัฒนาการสูงสุด</div><div class="big">${best?esc(best.key):'ไม่มีข้อมูล'}</div><div class="pair"><span>Pass Rate</span><span>${best?pct(best.b.passRate):'-'}</span></div><div class="trend good">${best?diffText(best.d):'ไม่สามารถคำนวณได้'}</div></article>`].join('');}
function renderSnapshots(){const a=metric(filtered('2568')),b=metric(filtered('2569')),groups=compareRows('subjectGroup').filter(x=>x.d!=null).sort((x,y)=>y.d-x.d), grades=compareRows('gradeLevel').filter(x=>x.d!=null).sort((x,y)=>y.d-x.d);const bad=[...groups,...grades].filter(x=>x.d<0).sort((x,y)=>x.d-y.d)[0];$('#snapshots').innerHTML=`<article class="snapshot"><b>พัฒนาการเด่น</b><p>ภาพรวมผ่านเกณฑ์ ${b.passRate>=a.passRate?'เพิ่มขึ้น':'ลดลง'} ${fmt(Math.abs((b.passRate??0)-(a.passRate??0)))} จุดร้อยละ</p></article><article class="snapshot"><b>กลุ่มสาระเด่น</b><p>${groups[0]?`${esc(groups[0].key)} ${diffText(groups[0].d)}`:'ไม่มีข้อมูล'}</p></article><article class="snapshot"><b>ประเด็นที่ควรพัฒนา</b><p>${bad?`${esc(bad.key)} ${diffText(bad.d)}`:'ไม่พบระดับชั้นหรือกลุ่มสาระที่มีผลสัมฤทธิ์ลดลง'}</p></article>`;}
function destroy(name){if(state.charts[name]){state.charts[name].destroy();delete state.charts[name];}}
function mkChart(name,id,config){destroy(name);state.charts[name]=new Chart($(id),config);}
function chartDefaults(){return {responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{font:{family:'Sarabun'}}},tooltip:{titleFont:{family:'Sarabun'},bodyFont:{family:'Sarabun'}}},scales:{x:{ticks:{font:{family:'Sarabun'}},grid:{display:false}},y:{ticks:{font:{family:'Sarabun'}},grid:{color:'#e2e8f0'}}}}}
function renderGradeChart(){const rows=compareRows('gradeLevel').sort((a,b)=>parseInt(a.key.replace(/\D/g,''))-parseInt(b.key.replace(/\D/g,'')));const opt=chartDefaults();opt.scales.y.min=0;opt.scales.y.max=100;opt.scales.y.ticks.callback=v=>v+'%';mkChart('grade','#gradeChart',{type:'bar',data:{labels:rows.map(x=>x.key),datasets:[{label:'1/2568',data:rows.map(x=>x.a.passRate),backgroundColor:COLORS.old,borderRadius:5},{label:'1/2569',data:rows.map(x=>x.b.passRate),backgroundColor:COLORS.now,borderRadius:5}]},options:opt});const improved=rows.filter(x=>x.d>0).length,best=[...rows].filter(x=>x.d!=null).sort((a,b)=>b.d-a.d)[0];$('#gradeInsight').textContent=best?`${improved} จาก ${rows.length} ระดับชั้นมีร้อยละผ่านเกณฑ์เพิ่มขึ้น · พัฒนาการสูงสุด ${best.key} เพิ่มขึ้น ${fmt(best.d)} จุดร้อยละ`:'ไม่มีข้อมูล';
  mkChart('gradeDetail','#gradeDetailChart',{type:'bar',data:{labels:rows.map(x=>x.key),datasets:[{label:'2568',data:rows.map(x=>x.a.passRate),backgroundColor:COLORS.old},{label:'2569',data:rows.map(x=>x.b.passRate),backgroundColor:COLORS.now}]},options:opt});
  $('#gradeTable').innerHTML=tableHTML(['ระดับชั้น','ผ่าน 68','ผ่าน 69','ผลต่าง','GPA 68','GPA 69','3+ 68','3+ 69','0/ร/มส 68','0/ร/มส 69'],rows.map(x=>[x.key,pct(x.a.passRate),pct(x.b.passRate),diffText(x.d),fmt(x.a.gpa),fmt(x.b.gpa),pct(x.a.g3Rate),pct(x.b.g3Rate),x.a.fail,x.b.fail]));}
function distData(records){const total=sum(records,r=>sum(ALL,k=>r.grades[k]||0));if(!total)return [0,0,0,0];const ex=sum(records,r=>(r.grades['4']||0)+(r.grades['3.5']||0));const good=sum(records,r=>(r.grades['3']||0)+(r.grades['2.5']||0));const pass=sum(records,r=>(r.grades['2']||0)+(r.grades['1.5']||0)+(r.grades['1']||0));const fail=sum(records,r=>(r.grades['0']||0)+(r.grades['ร']||0)+(r.grades['มส']||0));return [ex,good,pass,fail].map(v=>v/total*100);}
function renderDistribution(){const d68=distData(filtered('2568')),d69=distData(filtered('2569')), opt=chartDefaults();opt.indexAxis='y';opt.scales.x.stacked=true;opt.scales.y.stacked=true;opt.scales.x.max=100;opt.scales.x.ticks.callback=v=>v+'%';mkChart('dist','#distChart',{type:'bar',data:{labels:['1/2568','1/2569'],datasets:[{label:'ดีเยี่ยม 3.50–4.00',data:[d68[0],d69[0]],backgroundColor:COLORS.green},{label:'ดี 2.50–3.00',data:[d68[1],d69[1]],backgroundColor:COLORS.now},{label:'ผ่าน 1.00–2.00',data:[d68[2],d69[2]],backgroundColor:COLORS.orange},{label:'ไม่ผ่าน 0/ร/มส',data:[d68[3],d69[3]],backgroundColor:COLORS.red}]},options:opt});}
function renderSubjectChart(){const rows=compareRows('subjectGroup').filter(x=>ACADEMIC_GROUPS.includes(x.key)).sort((a,b)=>(b.d??-999)-(a.d??-999));const opt=chartDefaults();opt.indexAxis='y';opt.scales.x.min=0;opt.scales.x.max=100;opt.scales.x.ticks.callback=v=>v+'%';mkChart('subject','#subjectChart',{type:'bar',data:{labels:rows.map(x=>x.key),datasets:[{label:'1/2568',data:rows.map(x=>x.a.passRate),backgroundColor:COLORS.old},{label:'1/2569',data:rows.map(x=>x.b.passRate),backgroundColor:COLORS.now}]},options:opt});}
function heatColor(v){if(v==null)return '#f1f5f9';if(v>=5)return '#86efac';if(v>=3)return '#bbf7d0';if(v<=-5)return '#fca5a5';if(v<=-3)return '#fed7aa';return '#fef3c7'}
function renderHeatmap(){const levels=['ม.1','ม.2','ม.3','ม.4','ม.5','ม.6'];let html='<table class="heat-table"><thead><tr><th>กลุ่มสาระ</th>'+levels.map(x=>`<th>${x}</th>`).join('')+'</tr></thead><tbody>';for(const g of ACADEMIC_GROUPS){html+=`<tr><th>${g}</th>`;for(const lv of levels){const save={...state};state.grade=lv;state.group=g;state.subject='all';const a=metric(filtered('2568')),b=metric(filtered('2569'));Object.assign(state,save);const d=a.passRate!=null&&b.passRate!=null?b.passRate-a.passRate:null;html+=`<td style="background:${heatColor(d)}" title="${g} ${lv}: ${diffText(d)}">${d==null?'—':(d>0?'+':'')+fmt(d)}</td>`;}html+='</tr>';}html+='</tbody></table>';$('#heatmap').innerHTML=html;}
function renderRisk(){const a=metric(filtered('2568')),b=metric(filtered('2569'));const cards=[['0',a.zero,b.zero],['ร',a.r,b.r],['มส',a.ms,b.ms],['รวม 0/ร/มส',a.fail,b.fail]];$('#riskCards').innerHTML=cards.map(([lab,x,y])=>`<article class="riskcard"><div class="label">${lab}</div><div class="riskvalue">${fmt(y,0)} รายการ</div><div class="pair">2568: ${fmt(x,0)} · 2569: ${fmt(y,0)}</div><div class="trend ${trendClass(y-x,false)}">${y<x?'▼ ลดลง':y>x?'▲ เพิ่มขึ้น':'− คงที่'} ${fmt(Math.abs(y-x),0)} รายการ</div></article>`).join('');}
function subjectCompare(){const keys=[...new Set([...filtered('2568'),...filtered('2569')].map(r=>r.subjectCode).filter(Boolean))];return keys.map(code=>{const aRecs=filtered('2568').filter(r=>r.subjectCode===code),bRecs=filtered('2569').filter(r=>r.subjectCode===code);const base=bRecs[0]||aRecs[0];const a=metric(aRecs),b=metric(bRecs);return {code,name:base?.subjectName||'',level:base?.gradeLevel||'',group:base?.subjectGroup||'',a,b,d:a.passRate!=null&&b.passRate!=null?b.passRate-a.passRate:null,n68:a.total,n69:b.total};});}
function tableHTML(headers,rows){return `<table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">ไม่พบข้อมูลตามตัวกรองที่เลือก</td></tr>`}</tbody></table>`;}
function renderSubjectTable(){const rows=subjectCompare().sort((a,b)=>a.level.localeCompare(b.level,'th')||a.code.localeCompare(b.code,'th'));$('#subjectTable').innerHTML='<h3>ตารางรายวิชา</h3>'+tableHTML(['รหัสวิชา','รายวิชา','ชั้น','กลุ่มสาระ','ผ่าน 68','ผ่าน 69','ผลต่าง','3+ 68','3+ 69','GPA 68','GPA 69','0','ร','มส'],rows.map(x=>[x.code,x.name,x.level,x.group,pct(x.a.passRate),pct(x.b.passRate),diffText(x.d),pct(x.a.g3Rate),pct(x.b.g3Rate),fmt(x.a.gpa),fmt(x.b.gpa),x.b.zero,x.b.r,x.b.ms]));}
function renderDataTable(search=''){const q=search.trim().toLowerCase();const rows=subjectCompare().filter(x=>!q||[x.code,x.name,x.group,x.level].join(' ').toLowerCase().includes(q));$('#dataTable').innerHTML=tableHTML(['ชั้น','กลุ่มสาระ','รหัสวิชา','รายวิชา','รายการ 68','รายการ 69','ผ่าน 68','ผ่าน 69','ผลต่าง','GPA 68','GPA 69','3+ 68','3+ 69','0/ร/มส 68','0/ร/มส 69'],rows.map(x=>[x.level,x.group,x.code,x.name,x.n68,x.n69,pct(x.a.passRate),pct(x.b.passRate),diffText(x.d),fmt(x.a.gpa),fmt(x.b.gpa),pct(x.a.g3Rate),pct(x.b.g3Rate),x.a.fail,x.b.fail]));}
function rankingRows(){return subjectCompare().filter(x=>x.d!=null && Math.min(x.a.total||0,x.b.total||0)>=5);}
function renderSummary(){const a=metric(filtered('2568')),b=metric(filtered('2569')),grade=compareRows('gradeLevel').filter(x=>x.d!=null).sort((x,y)=>y.d-x.d), group=compareRows('subjectGroup').filter(x=>x.d!=null).sort((x,y)=>y.d-x.d), ranked=rankingRows();const top=[...ranked].sort((x,y)=>y.d-x.d).slice(0,5), watch=[...ranked].filter(x=>x.d<0).sort((x,y)=>x.d-y.d).slice(0,5);const passD=b.passRate!=null&&a.passRate!=null?b.passRate-a.passRate:null,g3D=b.g3Rate!=null&&a.g3Rate!=null?b.g3Rate-a.g3Rate:null,failD=b.fail-a.fail;$('#execSummary').innerHTML=`ผลการวิเคราะห์ผลสัมฤทธิ์ทางการเรียนภาคเรียนที่ 1 ปีการศึกษา 2569 เมื่อเปรียบเทียบกับภาคเรียนที่ 1 ปีการศึกษา 2568 ภายใต้ตัวกรองปัจจุบัน พบว่า ร้อยละผ่านเกณฑ์เปลี่ยนจาก <b>${pct(a.passRate)}</b> เป็น <b>${pct(b.passRate)}</b> (${diffText(passD)}). ผลการเรียน 0 / ร / มส เปลี่ยนจาก <b>${fmt(a.fail,0)}</b> เป็น <b>${fmt(b.fail,0)}</b> รายการ ${failD<0?'ซึ่งเป็นแนวโน้มที่ดีขึ้น':failD>0?'ซึ่งควรติดตาม':'คงที่'} ขณะที่เกรด 3 ขึ้นไปเปลี่ยนจาก <b>${pct(a.g3Rate)}</b> เป็น <b>${pct(b.g3Rate)}</b> (${diffText(g3D)}). ${grade[0]?`ระดับชั้นที่พัฒนาสูงสุดคือ <b>${grade[0].key}</b> ${diffText(grade[0].d)}.`:''} ${group[0]?`กลุ่มสาระที่พัฒนาสูงสุดคือ <b>${group[0].key}</b> ${diffText(group[0].d)}.`:''}`;
  const rec=[];if(passD!=null&&passD>=3)rec.push(['รักษาและต่อยอด','ถอดบทเรียนแนวปฏิบัติที่ส่งผลให้ร้อยละผ่านเกณฑ์เพิ่มขึ้น และนำไปแลกเปลี่ยนใน PLC']);if(watch.length)rec.push(['เร่งพัฒนา',`วิเคราะห์รายวิชาที่ผลสัมฤทธิ์ลดลง โดยเฉพาะ ${watch[0].name} (${watch[0].level}) และกำหนดแผนซ่อมเสริม`]);if(b.fail>0)rec.push(['ช่วยเหลือผู้เรียน','ติดตาม 0 / ร / มส เป็นรายวิชา กำหนดผู้รับผิดชอบและกรอบเวลาการแก้ผลการเรียน']);if(g3D!=null&&g3D>0)rec.push(['ยกระดับคุณภาพ','เกรด 3 ขึ้นไปเพิ่มขึ้น ควรรักษากิจกรรมที่ส่งเสริมการคิดวิเคราะห์และการประเมินเพื่อพัฒนา']);rec.push(['ติดตามผลรอบถัดไป','ใช้โครงสร้างข้อมูลรายบุคคลในรอบถัดไป เพื่อวิเคราะห์ Unique Student กลุ่มเสี่ยงและติดตามต่อเนื่อง']);$('#recommendations').innerHTML=rec.map(x=>`<div class="rec"><b>${x[0]}</b><br>${x[1]}</div>`).join('');
  const rankHtml=(arr,negative=false)=>arr.length?arr.map((x,i)=>`<div class="rankrow"><span class="ranknum">${i+1}</span><div><b>${esc(x.level)} — ${esc(x.name)}</b><small>${esc(x.group)} · ${pct(x.a.passRate)} → ${pct(x.b.passRate)}</small></div><strong style="color:${negative?COLORS.red:COLORS.green}">${diffText(x.d)}</strong></div>`).join(''):'<div class="notice">ไม่พบรายการที่เข้าเกณฑ์</div>';$('#topImprove').innerHTML=rankHtml(top);$('#watchList').innerHTML=rankHtml(watch,true);}
function renderQuality(){const a=DATA.audit||{};$('#qualityContent').innerHTML=`<div class="grid-2"><div><h3>1/2568</h3><p>Records หลังตัดหัวตารางซ้ำ: <b>${a.rows?.['2568']??'-'}</b></p><p>Academic rows: <b>${a.academicRows?.['2568']??'-'}</b></p></div><div><h3>1/2569</h3><p>Records หลังตัดหัวตารางซ้ำ: <b>${a.rows?.['2569']??'-'}</b></p><p>Academic rows: <b>${a.academicRows?.['2569']??'-'}</b></p></div></div><h3>คอลัมน์ที่ตรวจพบ</h3><p>${(a.columns||[]).map(esc).join(' · ')}</p><h3>ข้อสังเกตจากข้อมูล</h3><ul>${(a.limitations||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;}
function renderScope(){const parts=[];if(state.grade!=='all')parts.push(state.grade);if(state.group!=='all')parts.push(state.group);if(state.subject!=='all'){const r=DATA.records.find(x=>x.subjectCode===state.subject);parts.push(r?`${r.subjectCode} ${r.subjectName}`:state.subject)}$('#scopeLabel').textContent=parts.length?parts.join(' · '):'ทั้งโรงเรียน';}
function renderAll(){renderScope();renderKPIs();renderSnapshots();renderGradeChart();renderDistribution();renderSubjectChart();renderHeatmap();renderRisk();renderSubjectTable();renderDataTable($('#tableSearch')?.value||'');renderSummary();}
function fillFilters(){const grades=['ม.1','ม.2','ม.3','ม.4','ม.5','ม.6'].filter(g=>DATA.records.some(r=>r.gradeLevel===g));$('#classFilter').insertAdjacentHTML('beforeend',grades.map(x=>`<option>${x}</option>`).join(''));$('#groupFilter').insertAdjacentHTML('beforeend',ACADEMIC_GROUPS.filter(g=>DATA.records.some(r=>r.subjectGroup===g)).map(x=>`<option>${x}</option>`).join(''));updateSubjects();}
function updateSubjects(){const sel=$('#subjectFilter'),cur=state.subject;sel.innerHTML='<option value="all">ทุกรายวิชา</option>';const rec=academic(DATA.records).filter(r=>(state.grade==='all'||r.gradeLevel===state.grade)&&(state.group==='all'||r.subjectGroup===state.group));const map=new Map;rec.forEach(r=>map.set(r.subjectCode,`${r.subjectCode} — ${r.subjectName}`));[...map].sort((a,b)=>a[1].localeCompare(b[1],'th')).forEach(([v,t])=>sel.insertAdjacentHTML('beforeend',`<option value="${esc(v)}">${esc(t)}</option>`));if([...sel.options].some(o=>o.value===cur)){sel.value=cur}else{state.subject='all';sel.value='all';}}
function nav(){const items=[['overview','ภาพรวมผู้บริหาร'],['grades','ระดับชั้นและห้อง'],['subjects','กลุ่มสาระ / รายวิชา'],['risk','0 / ร / มส'],['table','ตารางข้อมูล'],['summary','บทสรุปและข้อเสนอ']];$('#nav').innerHTML=items.map(([id,t])=>`<button class="navbtn ${id==='overview'?'active':''}" data-page="${id}">${t}</button>`).join('');$('#nav').addEventListener('click',e=>{const b=e.target.closest('.navbtn');if(!b)return;state.page=b.dataset.page;$$('.navbtn').forEach(x=>x.classList.toggle('active',x===b));$$('.page').forEach(x=>x.classList.toggle('active',x.dataset.page===state.page));document.body.classList.remove('sidebar-open');});}
function csv(){const rows=subjectCompare(),head=['ชั้น','กลุ่มสาระ','รหัสวิชา','รายวิชา','ผ่าน2568','ผ่าน2569','ผลต่างจุดร้อยละ','GPA2568','GPA2569','0รสมส2568','0รสมส2569'];const lines=[head,...rows.map(x=>[x.level,x.group,x.code,x.name,x.a.passRate,x.b.passRate,x.d,x.a.gpa,x.b.gpa,x.a.fail,x.b.fail])].map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(','));const blob=new Blob(['\uFEFF'+lines.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='PSW_Academic_Dashboard_Data.csv';a.click();URL.revokeObjectURL(a.href);}
async function exportPNG(){if(!window.html2canvas)return alert('ไม่สามารถโหลด html2canvas ได้ กรุณาเชื่อมต่ออินเทอร์เน็ตแล้วลองใหม่');const el=$('#dashboardContent');const canvas=await html2canvas(el,{scale:2,backgroundColor:'#fff',useCORS:true,ignoreElements:e=>e.classList?.contains('no-export')});const a=document.createElement('a');a.download=`PSW_Academic_Dashboard_${state.grade==='all'?'School':state.grade.replace('.','')}_1-2568_vs_1-2569.png`;a.href=canvas.toDataURL('image/png');a.click();}
async function exportPDF(){if(!window.html2canvas||!window.jspdf)return alert('ไม่สามารถโหลดไลบรารี PDF ได้ กรุณาเชื่อมต่ออินเทอร์เน็ตแล้วลองใหม่');const {jsPDF}=window.jspdf,pdf=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),pages=['overview','grades','subjects','risk','summary'];const current=state.page;for(let i=0;i<pages.length;i++){showPage(pages[i]);await new Promise(r=>setTimeout(r,150));const canvas=await html2canvas(document.querySelector(`.page[data-page="${pages[i]}"]`),{scale:1.5,backgroundColor:'#fff'});const img=canvas.toDataURL('image/jpeg',.92),pw=297,ph=210,margin=7,ratio=Math.min((pw-margin*2)/canvas.width,(ph-margin*2)/canvas.height),w=canvas.width*ratio,h=canvas.height*ratio;if(i)pdf.addPage();pdf.setFontSize(8);pdf.text('โรงเรียนโพธิ์ศรีสว่างวิทยา',margin,5.5);pdf.addImage(img,'JPEG',margin,9,w,h);pdf.text(`Academic Achievement Dashboard · 1/2568 vs 1/2569 · ${i+1}/${pages.length}`,margin,207)}showPage(current);pdf.save('PSW_Academic_Dashboard_1-2568_vs_1-2569.pdf');}
function showPage(id){state.page=id;$$('.page').forEach(x=>x.classList.toggle('active',x.dataset.page===id));$$('.navbtn').forEach(x=>x.classList.toggle('active',x.dataset.page===id));}
const scenePages=['overview','overview','subjects','subjects','overview','risk','summary','summary'];
function enterPresent(){document.body.classList.add('presenting');state.scene=0;showScene();document.documentElement.requestFullscreen?.().catch(()=>{});}
function showScene(){const p=scenePages[state.scene];$$('.page').forEach(x=>x.classList.remove('presentation-page'));const el=document.querySelector(`.page[data-page="${p}"]`);el.classList.add('presentation-page');$('#sceneNo').textContent=`${state.scene+1} / 8`;setTimeout(()=>Object.values(state.charts).forEach(c=>c.resize()),100);}
function exitPresent(){document.body.classList.remove('presenting');$$('.page').forEach(x=>x.classList.remove('presentation-page'));showPage(state.page);if(document.fullscreenElement)document.exitFullscreen?.();}
function nextScene(d){state.scene=Math.max(0,Math.min(7,state.scene+d));showScene();}
function wire(){
  $('#classFilter').addEventListener('change',e=>{state.grade=e.target.value;updateSubjects();renderAll()});$('#groupFilter').addEventListener('change',e=>{state.group=e.target.value;updateSubjects();renderAll()});$('#subjectFilter').addEventListener('change',e=>{state.subject=e.target.value;renderAll()});$('#resetBtn').onclick=()=>{state.grade=state.group=state.subject='all';$('#classFilter').value=$('#groupFilter').value='all';updateSubjects();renderAll()};$('#qualityBtn').onclick=()=>$('#modal').classList.add('open');$('#modalClose').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('open')};$('#tableSearch').addEventListener('input',e=>renderDataTable(e.target.value));$('#csvBtn').onclick=csv;$('#pngBtn').onclick=exportPNG;$('#pdfBtn').onclick=exportPDF;$('#presentBtn').onclick=enterPresent;$('#exitPresent').onclick=exitPresent;$('#nextScene').onclick=()=>nextScene(1);$('#prevScene').onclick=()=>nextScene(-1);$('#menuBtn').onclick=()=>document.body.classList.toggle('sidebar-open');document.addEventListener('keydown',e=>{if(!document.body.classList.contains('presenting'))return;if(e.key==='ArrowRight')nextScene(1);if(e.key==='ArrowLeft')nextScene(-1);if(e.key==='Escape')exitPresent()});}
function boot(){nav();fillFilters();renderQuality();wire();const msgs=['กำลังตรวจสอบข้อมูล...','กำลังสร้างตัวชี้วัด...','กำลังสร้าง Dashboard...'];let i=0;const t=setInterval(()=>{$('#loadingText').textContent=msgs[Math.min(++i,msgs.length-1)]},220);setTimeout(()=>{clearInterval(t);renderAll();$('#loading').style.display='none'},650);}
if(!DATA.records?.length){$('#loading').innerHTML='<div class="notice"><h2>ไม่พบข้อมูล</h2><p>ไม่สามารถโหลด data.js ได้</p></div>'}else boot();
})();
